language: ruby
rvm:
  - 2.7
branches:
  except:
  - master
branches:
  only:
  - sourceFiles
script:
  - bundle install
  - bundle exec jekyll clean
  - bundle exec jekyll build
after_success:
  - bash deploy.sh
env:
  global:
    - secure: $GH_TOKEN
