language: ruby
rvm:
  - 2.2
branches:
  except:
  - master
branches:
  only:
  - sourceFiles
script:
  - gem install jekyll -v '3.1.3'
  - bundle install
  - bundle exec jekyll clean
  - bundle exec jekyll build
after_success:
  - bash deploy.sh
env:
  global:
    - secure: $GH_TOKEN